package com.kk.mybatis.model;

import java.util.Date;

public class Ruler {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_ruler.id
     *
     * @mbg.generated Tue Nov 26 19:25:50 CST 2019
     */
    private Long id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_ruler.parent_id
     *
     * @mbg.generated Tue Nov 26 19:25:50 CST 2019
     */
    private Long parentId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_ruler.name
     *
     * @mbg.generated Tue Nov 26 19:25:50 CST 2019
     */
    private String name;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_ruler.code
     *
     * @mbg.generated Tue Nov 26 19:25:50 CST 2019
     */
    private String code;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_ruler.ruler_type
     *
     * @mbg.generated Tue Nov 26 19:25:50 CST 2019
     */
    private String rulerType;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_ruler.ruler_script
     *
     * @mbg.generated Tue Nov 26 19:25:50 CST 2019
     */
    private String rulerScript;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_ruler.script_language
     *
     * @mbg.generated Tue Nov 26 19:25:50 CST 2019
     */
    private String scriptLanguage;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_ruler.warn_types
     *
     * @mbg.generated Tue Nov 26 19:25:50 CST 2019
     */
    private String warnTypes;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_ruler.analyze_field
     *
     * @mbg.generated Tue Nov 26 19:25:50 CST 2019
     */
    private String analyzeField;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_ruler.ruler_cron
     *
     * @mbg.generated Tue Nov 26 19:25:50 CST 2019
     */
    private String rulerCron;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_ruler.business_sign
     *
     * @mbg.generated Tue Nov 26 19:25:50 CST 2019
     */
    private String businessSign;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_ruler.template
     *
     * @mbg.generated Tue Nov 26 19:25:50 CST 2019
     */
    private Short template;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_ruler.grade_type
     *
     * @mbg.generated Tue Nov 26 19:25:50 CST 2019
     */
    private String gradeType;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_ruler.max_value
     *
     * @mbg.generated Tue Nov 26 19:25:50 CST 2019
     */
    private Short maxValue;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_ruler.status
     *
     * @mbg.generated Tue Nov 26 19:25:50 CST 2019
     */
    private Short status;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_ruler.banned_ip
     *
     * @mbg.generated Tue Nov 26 19:25:50 CST 2019
     */
    private Short bannedIp;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_ruler.banned_uid
     *
     * @mbg.generated Tue Nov 26 19:25:50 CST 2019
     */
    private Short bannedUid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_ruler.aliyun_safe_sdk
     *
     * @mbg.generated Tue Nov 26 19:25:50 CST 2019
     */
    private Short aliyunSafeSdk;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_ruler.create_time
     *
     * @mbg.generated Tue Nov 26 19:25:50 CST 2019
     */
    private Date createTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_ruler.creator
     *
     * @mbg.generated Tue Nov 26 19:25:50 CST 2019
     */
    private String creator;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_ruler.modify_time
     *
     * @mbg.generated Tue Nov 26 19:25:50 CST 2019
     */
    private Date modifyTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_ruler.modifier
     *
     * @mbg.generated Tue Nov 26 19:25:50 CST 2019
     */
    private String modifier;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_ruler.id
     *
     * @return the value of tbl_ruler.id
     *
     * @mbg.generated Tue Nov 26 19:25:50 CST 2019
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_ruler.id
     *
     * @param id the value for tbl_ruler.id
     *
     * @mbg.generated Tue Nov 26 19:25:50 CST 2019
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_ruler.parent_id
     *
     * @return the value of tbl_ruler.parent_id
     *
     * @mbg.generated Tue Nov 26 19:25:50 CST 2019
     */
    public Long getParentId() {
        return parentId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_ruler.parent_id
     *
     * @param parentId the value for tbl_ruler.parent_id
     *
     * @mbg.generated Tue Nov 26 19:25:50 CST 2019
     */
    public void setParentId(Long parentId) {
        this.parentId = parentId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_ruler.name
     *
     * @return the value of tbl_ruler.name
     *
     * @mbg.generated Tue Nov 26 19:25:50 CST 2019
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_ruler.name
     *
     * @param name the value for tbl_ruler.name
     *
     * @mbg.generated Tue Nov 26 19:25:50 CST 2019
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_ruler.code
     *
     * @return the value of tbl_ruler.code
     *
     * @mbg.generated Tue Nov 26 19:25:50 CST 2019
     */
    public String getCode() {
        return code;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_ruler.code
     *
     * @param code the value for tbl_ruler.code
     *
     * @mbg.generated Tue Nov 26 19:25:50 CST 2019
     */
    public void setCode(String code) {
        this.code = code == null ? null : code.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_ruler.ruler_type
     *
     * @return the value of tbl_ruler.ruler_type
     *
     * @mbg.generated Tue Nov 26 19:25:50 CST 2019
     */
    public String getRulerType() {
        return rulerType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_ruler.ruler_type
     *
     * @param rulerType the value for tbl_ruler.ruler_type
     *
     * @mbg.generated Tue Nov 26 19:25:50 CST 2019
     */
    public void setRulerType(String rulerType) {
        this.rulerType = rulerType == null ? null : rulerType.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_ruler.ruler_script
     *
     * @return the value of tbl_ruler.ruler_script
     *
     * @mbg.generated Tue Nov 26 19:25:50 CST 2019
     */
    public String getRulerScript() {
        return rulerScript;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_ruler.ruler_script
     *
     * @param rulerScript the value for tbl_ruler.ruler_script
     *
     * @mbg.generated Tue Nov 26 19:25:50 CST 2019
     */
    public void setRulerScript(String rulerScript) {
        this.rulerScript = rulerScript == null ? null : rulerScript.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_ruler.script_language
     *
     * @return the value of tbl_ruler.script_language
     *
     * @mbg.generated Tue Nov 26 19:25:50 CST 2019
     */
    public String getScriptLanguage() {
        return scriptLanguage;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_ruler.script_language
     *
     * @param scriptLanguage the value for tbl_ruler.script_language
     *
     * @mbg.generated Tue Nov 26 19:25:50 CST 2019
     */
    public void setScriptLanguage(String scriptLanguage) {
        this.scriptLanguage = scriptLanguage == null ? null : scriptLanguage.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_ruler.warn_types
     *
     * @return the value of tbl_ruler.warn_types
     *
     * @mbg.generated Tue Nov 26 19:25:50 CST 2019
     */
    public String getWarnTypes() {
        return warnTypes;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_ruler.warn_types
     *
     * @param warnTypes the value for tbl_ruler.warn_types
     *
     * @mbg.generated Tue Nov 26 19:25:50 CST 2019
     */
    public void setWarnTypes(String warnTypes) {
        this.warnTypes = warnTypes == null ? null : warnTypes.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_ruler.analyze_field
     *
     * @return the value of tbl_ruler.analyze_field
     *
     * @mbg.generated Tue Nov 26 19:25:50 CST 2019
     */
    public String getAnalyzeField() {
        return analyzeField;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_ruler.analyze_field
     *
     * @param analyzeField the value for tbl_ruler.analyze_field
     *
     * @mbg.generated Tue Nov 26 19:25:50 CST 2019
     */
    public void setAnalyzeField(String analyzeField) {
        this.analyzeField = analyzeField == null ? null : analyzeField.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_ruler.ruler_cron
     *
     * @return the value of tbl_ruler.ruler_cron
     *
     * @mbg.generated Tue Nov 26 19:25:50 CST 2019
     */
    public String getRulerCron() {
        return rulerCron;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_ruler.ruler_cron
     *
     * @param rulerCron the value for tbl_ruler.ruler_cron
     *
     * @mbg.generated Tue Nov 26 19:25:50 CST 2019
     */
    public void setRulerCron(String rulerCron) {
        this.rulerCron = rulerCron == null ? null : rulerCron.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_ruler.business_sign
     *
     * @return the value of tbl_ruler.business_sign
     *
     * @mbg.generated Tue Nov 26 19:25:50 CST 2019
     */
    public String getBusinessSign() {
        return businessSign;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_ruler.business_sign
     *
     * @param businessSign the value for tbl_ruler.business_sign
     *
     * @mbg.generated Tue Nov 26 19:25:50 CST 2019
     */
    public void setBusinessSign(String businessSign) {
        this.businessSign = businessSign == null ? null : businessSign.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_ruler.template
     *
     * @return the value of tbl_ruler.template
     *
     * @mbg.generated Tue Nov 26 19:25:50 CST 2019
     */
    public Short getTemplate() {
        return template;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_ruler.template
     *
     * @param template the value for tbl_ruler.template
     *
     * @mbg.generated Tue Nov 26 19:25:50 CST 2019
     */
    public void setTemplate(Short template) {
        this.template = template;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_ruler.grade_type
     *
     * @return the value of tbl_ruler.grade_type
     *
     * @mbg.generated Tue Nov 26 19:25:50 CST 2019
     */
    public String getGradeType() {
        return gradeType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_ruler.grade_type
     *
     * @param gradeType the value for tbl_ruler.grade_type
     *
     * @mbg.generated Tue Nov 26 19:25:50 CST 2019
     */
    public void setGradeType(String gradeType) {
        this.gradeType = gradeType == null ? null : gradeType.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_ruler.max_value
     *
     * @return the value of tbl_ruler.max_value
     *
     * @mbg.generated Tue Nov 26 19:25:50 CST 2019
     */
    public Short getMaxValue() {
        return maxValue;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_ruler.max_value
     *
     * @param maxValue the value for tbl_ruler.max_value
     *
     * @mbg.generated Tue Nov 26 19:25:50 CST 2019
     */
    public void setMaxValue(Short maxValue) {
        this.maxValue = maxValue;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_ruler.status
     *
     * @return the value of tbl_ruler.status
     *
     * @mbg.generated Tue Nov 26 19:25:50 CST 2019
     */
    public Short getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_ruler.status
     *
     * @param status the value for tbl_ruler.status
     *
     * @mbg.generated Tue Nov 26 19:25:50 CST 2019
     */
    public void setStatus(Short status) {
        this.status = status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_ruler.banned_ip
     *
     * @return the value of tbl_ruler.banned_ip
     *
     * @mbg.generated Tue Nov 26 19:25:50 CST 2019
     */
    public Short getBannedIp() {
        return bannedIp;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_ruler.banned_ip
     *
     * @param bannedIp the value for tbl_ruler.banned_ip
     *
     * @mbg.generated Tue Nov 26 19:25:50 CST 2019
     */
    public void setBannedIp(Short bannedIp) {
        this.bannedIp = bannedIp;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_ruler.banned_uid
     *
     * @return the value of tbl_ruler.banned_uid
     *
     * @mbg.generated Tue Nov 26 19:25:50 CST 2019
     */
    public Short getBannedUid() {
        return bannedUid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_ruler.banned_uid
     *
     * @param bannedUid the value for tbl_ruler.banned_uid
     *
     * @mbg.generated Tue Nov 26 19:25:50 CST 2019
     */
    public void setBannedUid(Short bannedUid) {
        this.bannedUid = bannedUid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_ruler.aliyun_safe_sdk
     *
     * @return the value of tbl_ruler.aliyun_safe_sdk
     *
     * @mbg.generated Tue Nov 26 19:25:50 CST 2019
     */
    public Short getAliyunSafeSdk() {
        return aliyunSafeSdk;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_ruler.aliyun_safe_sdk
     *
     * @param aliyunSafeSdk the value for tbl_ruler.aliyun_safe_sdk
     *
     * @mbg.generated Tue Nov 26 19:25:50 CST 2019
     */
    public void setAliyunSafeSdk(Short aliyunSafeSdk) {
        this.aliyunSafeSdk = aliyunSafeSdk;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_ruler.create_time
     *
     * @return the value of tbl_ruler.create_time
     *
     * @mbg.generated Tue Nov 26 19:25:50 CST 2019
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_ruler.create_time
     *
     * @param createTime the value for tbl_ruler.create_time
     *
     * @mbg.generated Tue Nov 26 19:25:50 CST 2019
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_ruler.creator
     *
     * @return the value of tbl_ruler.creator
     *
     * @mbg.generated Tue Nov 26 19:25:50 CST 2019
     */
    public String getCreator() {
        return creator;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_ruler.creator
     *
     * @param creator the value for tbl_ruler.creator
     *
     * @mbg.generated Tue Nov 26 19:25:50 CST 2019
     */
    public void setCreator(String creator) {
        this.creator = creator == null ? null : creator.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_ruler.modify_time
     *
     * @return the value of tbl_ruler.modify_time
     *
     * @mbg.generated Tue Nov 26 19:25:50 CST 2019
     */
    public Date getModifyTime() {
        return modifyTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_ruler.modify_time
     *
     * @param modifyTime the value for tbl_ruler.modify_time
     *
     * @mbg.generated Tue Nov 26 19:25:50 CST 2019
     */
    public void setModifyTime(Date modifyTime) {
        this.modifyTime = modifyTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_ruler.modifier
     *
     * @return the value of tbl_ruler.modifier
     *
     * @mbg.generated Tue Nov 26 19:25:50 CST 2019
     */
    public String getModifier() {
        return modifier;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_ruler.modifier
     *
     * @param modifier the value for tbl_ruler.modifier
     *
     * @mbg.generated Tue Nov 26 19:25:50 CST 2019
     */
    public void setModifier(String modifier) {
        this.modifier = modifier == null ? null : modifier.trim();
    }

    @Override
    public String toString() {
        return "Ruler{" +
                "id=" + id +
                ", name='" + name + '\'' +
                ", code='" + code + '\'' +
                '}';
    }
}