package com.kk.mybatis.mapper;

import com.kk.mybatis.model.Group;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.annotations.Select;

import java.util.Date;
import java.util.List;

public interface GroupMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_group
     *
     * @mbg.generated Wed Nov 20 10:24:01 CST 2019
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_group
     *
     * @mbg.generated Wed Nov 20 10:24:01 CST 2019
     */
    int insert(Group record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_group
     *
     * @mbg.generated Wed Nov 20 10:24:01 CST 2019
     */
    int insertSelective(Group record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_group
     *
     * @mbg.generated Wed Nov 20 10:24:01 CST 2019
     */
    Group selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_group
     *
     * @mbg.generated Wed Nov 20 10:24:01 CST 2019
     */
    int updateByPrimaryKeySelective(Group record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_group
     *
     * @mbg.generated Wed Nov 20 10:24:01 CST 2019
     */
    int updateByPrimaryKey(Group record);

    @Select("SELECT * FROM tbl_group WHERE name = #{name}")
    Group selectGroupByName(String name);

    int updateNameById(@Param("name") String name, @Param("id")Long id);

    int updateNameByPluginById(@Param("name") String name, @Param("id")Long id, @Param("modifyTime") Date modifyTime, @Param("modifier")String modifier);

    Group selectTypeHandlerNameById(long id);

    List<Group> selectAll();
}