package com.kk.mybatis.mapper;

import com.kk.mybatis.model.Ruler;

public interface RulerMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_ruler
     *
     * @mbg.generated Tue Nov 26 19:25:50 CST 2019
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_ruler
     *
     * @mbg.generated Tue Nov 26 19:25:50 CST 2019
     */
    int insert(Ruler record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_ruler
     *
     * @mbg.generated Tue Nov 26 19:25:50 CST 2019
     */
    int insertSelective(Ruler record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_ruler
     *
     * @mbg.generated Tue Nov 26 19:25:50 CST 2019
     */
    Ruler selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_ruler
     *
     * @mbg.generated Tue Nov 26 19:25:50 CST 2019
     */
    int updateByPrimaryKeySelective(Ruler record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_ruler
     *
     * @mbg.generated Tue Nov 26 19:25:50 CST 2019
     */
    int updateByPrimaryKey(Ruler record);
}